# Generated by Django 5.2.17 on 2026-09-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Client Payment (Escrow In)'), ('payout', 'Lawyer Payout'), ('platform_fee', 'Platform Fee'), ('refund', 'Refund to Client'), ('fine_bonus', 'Fine Bonus to Client'), ('fine_penalty', 'Fine Penalty on Lawyer'), ('topup', 'Wallet Top-Up')], max_length=20),
        ),
    ]
